name: 'Documentation Improvement'
description: 'Improve the documentation because some developer will always thank you for that'
title: '📝 Documentation Improvement: '
body:
  - type: textarea
    id: description
    attributes:
      label: '📝 Description'
      description: 'A clear and concise description of what the documentation improvement is.'
      placeholder: 'The documentation is missing a section about...'
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: '🖼️ Screenshots'
      description: 'If applicable, add screenshots to help explain your problem.'
    validations:
      required: false
  - type: textarea
    id: extra-information
    attributes:
      label: '📋 Additional Information'
      description: 'Add any other context about the problem here.'
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation improvement report!